[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
rsontest = "hack test -q --feature-powerset --skip default -F arbitrary -F serde --ignore-unknown-features"

[env]
RUST_BACKTRACE = "1"
